### ISSUE TITLE
Kernel Freeze, after batman-adv is running for more then 8 hours  

### ISSUE THREAD

**Issue by aeickho** [freifunk-gluon/batman-adv-legacy#1] opened 2015-04-25 17:05 UTC
on Debian 7.2
Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.65-1+deb7u2

on VirtualBox  4.3.26

System Freeze, after batman-adv is running for more then 8 hours
----> BUG: unable to handle kernel NULL pointer dereference

Batman-Adv Version: 042e300adfaff2dc5a1a1bdfa09c2cfbc99a3dec

See Log:
https://gist.github.com/aeickho/5dd4fd0c13345cd195f4

**Comment by NeoRaider** [comment] 2015-04-27 00:51
How reproducible is this bug? Was it a one-time occurence, or do you see such crashes regularly?

**Comment by aeickho** [comment] 2015-04-30 10:49
yes it's reproducible. but the machine was successfully running for 4 days with no freeze after update to jessie. from last crash-> i have no log on syslog server (I had not yet been activated)

on the same host is a further machine and which makes no problems.

**Comment by NeoRaider** [comment] 2015-04-30 23:30
Are you building batman-adv yourself? If it occurs again, can you try going back to 5593dfac934e66b6ed8204b1efcf40f3c98359f2 (or alternatively, revert 7064bfe8d134a9c97a850eab945f8c6c3a5b9187 and 074ee9735f09107d60256cf4045dedd246f26d43)

**Comment by kjokjo** [comment] 2015-05-05 23:15
Kernelpanic after about 10 days uptime:

![screenshot_628](https://cloud.githubusercontent.com/assets/8742085/7484745/896371a4-f38c-11e4-87ed-1c3916bef3b8.png)


[    9.896887] batman_adv: B.A.T.M.A.N. advanced 2013.4.0 (compatibility version 14) loaded

ii  batctl           2013.4.0-1          amd64       B.A.T.M.A.N. advanced control and management tool
ii  batman-adv-dkms   2013.4.0-6    all        DKMS Source for the batman-advanced kernel module

Package: batman-adv-dkms
Source: batman-adv-kernelland
Version: 2013.4.0-6
Architecture: all
Maintainer: Matthias Schiffer <mschiffer@universe-factory.net>
Installed-Size: 645
Depends: dkms (>= 2.1.0.0)
Recommends: batctl
Homepage: http://www.open-mesh.net/
Priority: extra
Section: kernel
Filename: pool/main/b/batman-adv-kernelland/batman-adv-dkms_2013.4.0-6_all.deb
Size: 148354
SHA256: d6da925cd163792339fc6bb6fab3529656220fca62245614039717114f3140d2
SHA1: 429b24ef851b1184538d7dbfad0c0626161e7a9e
MD5sum: 28aacf08a06d58232e356b372a8f5ed5

**Comment by aeickho** [comment] 2015-05-06 12:16
I build myself batman from repro

5593dfac934e66b6ed8204b1efcf40f3c98359f2 
batman_adv: B.A.T.M.A.N. advanced 2013.4.0-9-g5593dfa-dirty (compatibility version 14) loaded 

is now running ... i'm waiting for the next Kernelpanic.

**Comment by aeickho** [comment] 2015-05-06 12:50
on another VM on the same host, I run batman_adv: BATMAN advanced 2013.4.0-13-gd040966-dirty

**Comment by aeickho** [comment] 2015-05-07 15:04
16:09] <kassio> neoraider: dein batman-adv-dkms Version: 2013.4.0-6 .. wie finde ich den die dazu passende git commit 
[16:13] <kassio> ich denke mal es ist der stand 042e300adfaff2dc5a1a1bdfa09c2cfbc99a3dec

**Comment by NeoRaider** [comment] 2015-05-07 17:58
The Debian package is 13713247f48bb3d2ac573ca27e316f5068560892, the  current HEAD of the legacy-vis branch (which is identical to 042e300adfaff2dc5a1a1bdfa09c2cfbc99a3dec except of the legacy-bis feature).

As the latest commits seem to be problematic, I'll revert them and update the Debian package.

**Comment by aeickho** [comment] 2015-05-08 07:59
>>batman_adv: B.A.T.M.A.N. advanced 2013.4.0-9-g5593dfa-dirty (compatibility version 14) loaded
>>is now running ... i'm waiting for the next Kernelpanic.

Kernelpanic after about 20 hours with (https://github.com/freifunk-gluon/batman-adv-legacy/commit/5593dfac934e66b6ed8204b1efcf40f3c98359f2)

**Comment by NeoRaider** [comment] 2015-05-09 02:22
Okay, so no recent patch has caused this behaviour.

@T-X, any idea?

**Comment by aeickho** [comment] 2015-05-11 14:18
Kernelpanic after about 3 days  with (5593dfa) 
![ffgoevm_055059](https://cloud.githubusercontent.com/assets/986535/7566826/5c3758a0-f7f9-11e4-832a-29d90511f1f0.png)

**Comment by T-X** [comment] 2015-05-11 15:29
@aeickho: How does your setup look like, how many nodes are involved? Can you reproduce it with just two or three nodes, too? If it might happen, then it should happen once an originator vansihes. So try it with two or three nodes, remove one and wait for 15 minutes. If that can trigger it reliably that that'd be handy for debugging.

@NeoRaider: No idea yet. Had been looking through the current batman-adv code for orig-node refcouting bugs a couple of days to fix that one bug but despite the ones I fixed I didn't find any others so far. Would be interesting to know, whether it still happens with a current batman-adv release, too since some parts got rewritten (for instance interface alternating).

**Comment by aeickho** [comment] 2015-05-12 11:47
idea:
-> problem @ "locking und double linked lists."
* there is no kernel panic o an 1 cpu machine 
* kernel panic is only on machines with more then 1 cpu

**Comment by aeickho** [comment] 2015-05-12 11:55
@T-X it is an node on ff-goettingen with nearly 300 active nodes.

**Comment by NeoRaider** [comment] 2015-05-12 12:09
Ah, an SMP issue would certainly explain why we don't see this issue a lot more often, as most communities run their gateways on uniprocessor machines. Maybe we can look at the locking at the WCW this weekend.

**Comment by T-X** [comment] 2015-05-12 13:45
Aiy, that's indeed very valuable information. @aeickho, if you feel like it you could rebuild the kernel with a few more debugging options in the "Kernel Hacking" section of a "make menuconfig" (e.g. options which have the word "locking" in them :) ). There are pretty clever things in there which if enabled can already detect quite some potential locking issues and inform you in dmesg before they actually happen.

If I recall correctly, then there were also some lock class patches in the past. We should check whether they were post 2013.4.0 and should get backported.

**Comment by aeickho** [comment] 2015-05-12 15:17
some additional info:
@hwhw has also an multiprocessor system and  has no problem with batman. but he used an  4.0.1 kernel.

**Comment by aeickho** [comment] 2015-07-11 13:27
https://twitter.com/freifunk_goe/status/619852115788308480

same mashine .. https://github.com/freifunk-gluon/batman-adv-legacy/issues/1#issuecomment-99257106

**Comment by aeickho** [comment] 2015-07-11 13:28
also no problem on an  multiprocessor system with 4.0.1

**Comment by aeickho** [comment] 2015-07-11 13:30
@hwhw bb1e497a16afb3225638fb8f0dbd66018548377a ?

**Comment by mweinelt** [comment] 2015-07-22 01:15
Does your `bat0` consist of multiple underlying interfaces by any chance?

**Comment by NeoRaider** [comment] 2016-05-31 15:41
ffcd5f2aa2a485cc7fc6496852050152cb89d9aa should fix this issue.

**Comment by NeoRaider** [comment] 2016-11-03 11:53
Closing, this should be fixed.

**Closed by NeoRaider** 2016-11-03 11:53 UTC
